# Generated by Django 5.1.3 on 2024-11-17 15:56

import admin_custom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0008_rename_created_at_room_created_at_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'permissions': [('can_view_offer', 'Can view offer'), ('can_create_offer', 'Can create offer'), ('can_edit_offer', 'Can edit offer'), ('can_delete_offer', 'Can delete offer')]},
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=admin_custom.models.get_image_upload_path_post),
        ),
    ]
