# Generated by Django 4.2.8 on 2024-12-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0010_commentpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Có sẵn'), ('occupied', 'Đang sử dụng'), ('maintenance', 'Đang sửa chữa')], default='available', max_length=20),
        ),
    ]
