# Generated by Django 5.1.4 on 2024-12-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_custom", "0012_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="permission",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("content_manager", "Content Manager"),
                    ("editor", "Editor"),
                ],
                default="editor",
                max_length=20,
            ),
        ),
    ]
