# Generated by Django 5.1.1 on 2024-11-01 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=250)),
                ('NoiDung', models.TextField(null=True)),
                ('NgayTao', models.DateField()),
                ('NguoiTao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaiVietChuyenMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThuTu', models.IntegerField()),
                ('BaiViet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlbaiviet.baiviet')),
                ('ChuyenMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlbaiviet.chuyenmuc')),
            ],
        ),
        migrations.AddField(
            model_name='baiviet',
            name='ChuyenMuc',
            field=models.ManyToManyField(through='qlbaiviet.BaiVietChuyenMuc', to='qlbaiviet.chuyenmuc'),
        ),
    ]
