# Generated by Django 5.1.3 on 2024-11-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0007_room_created_at_service_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_at',
            new_name='created_at_date',
        ),
    ]
